name: Download Calendar ICS

on:
  schedule:
    -  cron: "* */1 * * *" # every hour
  workflow_dispatch: # Allows manual triggering
permissions:
  contents: write
jobs:
  download-ics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Download ICS file
        run: |
          curl -L "${{ secrets.CALENDAR_URL }}" -o calendar.ics
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9 #install the python needed
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f action-scripts/requirements.txt ]; then pip install -r action-scripts/requirements.txt; fi
      - name: execute py script # run file
        run: |
          python action-scripts/newcaldata.py
      - name: Commit and push changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add calendar.ics
          git diff --quiet && git diff --staged --quiet || git commit -m "Update calendar.ics"
          git push
