name: authorize
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.GCS_KEY }}
      TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Vars
        run: echo $MY_ENV_VAR
      - name: runJS
        run: |
          node .github/actions-scripts/functions.js
