name: authorize
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.GCAL_KEY }}
    steps:
      - name: Vars
        run: echo $MY_ENV_VAR
      - name: Auth It
        run: |
          curl --request POST \
          --url https://accounts.google.com/o/oauth2/v2/auth \
          --header 'client_id: ${{ secrets.GCAL_KEY }}'
