name: authorize
on:
  push:
    branches:
      - main

jobs:
  my-job:
    runs-on: ubuntu-latest
    env:
      MY_ENV_VAR: ${{ secrets.GCAL_KEY }}
    steps:
      - name: My Step
        run: echo $MY_ENV_VAR
